# Generated by Django 4.1.5 on 2023-01-31 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_plant'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='toxic',
            field=models.TextField(blank=True, null=True),
        ),
    ]
