# Generated by Django 4.1.6 on 2023-02-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_water'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myplant',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='water',
            name='due',
            field=models.DateField(blank=True, null=True),
        ),
    ]
